obj-y += start.o setup.o arcksyms.o reboot.o irq.o
obj-y += stacktrace.o
obj-$(CONFIG_ARC_UNWIND) += unwind-hdr.o
obj-$(CONFIG_FRAME_POINTER) += unwind-fp.o
obj-$(CONFIG_ISA_ARCOMPACT) += intc-compact.o isr-compact.o
extra-y += arch-linker.lds asm-offsets.s
